package com.bkitmobile.poma.home.client;

public class WebsiteConfig {
	public static final String host = "http://bkitpoma.appspot.com/";
	public static final String homePage = "http://bkitpoma.appspot.com/home.jsp";

	public static final String[][] LANGUAGE = new String[][] {
			{ "vi", "Ti\u1EBFng Vi\u1EC7t" }, { "en", "English" } };

	public static final String[][] COUNTRIES_NAME = new String[][] {
			{ "AF", "Afghanistan" }, { "AL", "Albania" }, { "DZ", "Algeria" },
			{ "AS", "American Samoa" }, { "AD", "Andorra" },
			{ "AO", "Angola" }, { "AI", "Anguilla" }, { "AQ", "Antarctica" },
			{ "AG", "Antigua And Barbuda" }, { "AR", "Argentina" },
			{ "AM", "Armenia" }, { "AW", "Aruba" }, { "AU", "Australia" },
			{ "AT", "Austria" }, { "AZ", "Azerbaijan" }, { "BS", "Bahamas" },
			{ "BH", "Bahrain" }, { "BD", "Bangladesh" }, { "BB", "Barbados" },
			{ "BY", "Belarus" }, { "BE", "Belgium" }, { "BZ", "Belize" },
			{ "BJ", "Benin" }, { "BM", "Bermuda" }, { "BT", "Bhutan" },
			{ "BO", "Bolivia" }, { "BA", "Bosnia And Herzegovina" },
			{ "BW", "Botswana" }, { "BV", "Bouvet Island" },
			{ "BR", "Brazil" }, { "IO", "British Indian Ocean Territory" },
			{ "BN", "Brunei Darussalam" }, { "BG", "Bulgaria" },
			{ "BF", "Burkina Faso" }, { "BI", "Burundi" },
			{ "KH", "Cambodia" }, { "CM", "Cameroon" }, { "CA", "Canada" },
			{ "CV", "Cape Verde" }, { "KY", "Cayman Islands" },
			{ "CF", "Central African Republic" }, { "TD", "Chad" },
			{ "CL", "Chile" }, { "CN", "China" }, { "CX", "Christmas Island" },
			{ "CC", "Cocos (keeling) Islands" }, { "CO", "Colombia" },
			{ "KM", "Comoros" }, { "CG", "Congo" },
			{ "CD", "Congo, The Democratic Republic Of The" },
			{ "CK", "Cook Islands" }, { "CR", "Costa Rica" },
			{ "CI", "Cote D'ivoire" }, { "HR", "Croatia" }, { "CU", "Cuba" },
			{ "CY", "Cyprus" }, { "CZ", "Czech Republic" },
			{ "DK", "Denmark" }, { "DJ", "Djibouti" }, { "DM", "Dominica" },
			{ "DO", "Dominican Republic" }, { "TP", "East Timor" },
			{ "EC", "Ecuador" }, { "EG", "Egypt" }, { "SV", "El Salvador" },
			{ "GQ", "Equatorial Guinea" }, { "ER", "Eritrea" },
			{ "EE", "Estonia" }, { "ET", "Ethiopia" },
			{ "FK", "Falkland Islands (malvinas)" }, { "FO", "Faroe Islands" },
			{ "FJ", "Fiji" }, { "FI", "Finland" }, { "FR", "France" },
			{ "GF", "French Guiana" }, { "PF", "French Polynesia" },
			{ "TF", "French Southern Territories" }, { "GA", "Gabon" },
			{ "GM", "Gambia" }, { "GE", "Georgia" }, { "DE", "Germany" },
			{ "GH", "Ghana" }, { "GI", "Gibraltar" }, { "GR", "Greece" },
			{ "GL", "Greenland" }, { "GD", "Grenada" }, { "GP", "Guadeloupe" },
			{ "GU", "Guam" }, { "GT", "Guatemala" }, { "GN", "Guinea" },
			{ "GW", "Guinea-bissau" }, { "GY", "Guyana" }, { "HT", "Haiti" },
			{ "HM", "Heard Island And Mcdonald Islands" },
			{ "VA", "Holy See (vatican City State)" }, { "HN", "Honduras" },
			{ "HK", "Hong Kong" }, { "HU", "Hungary" }, { "IS", "Iceland" },
			{ "IN", "India" }, { "ID", "Indonesia" },
			{ "IR", "Iran, Islamic Republic Of" }, { "IQ", "Iraq" },
			{ "IE", "Ireland" }, { "IL", "Israel" }, { "IT", "Italy" },
			{ "JM", "Jamaica" }, { "JP", "Japan" }, { "JO", "Jordan" },
			{ "KZ", "Kazakstan" }, { "KE", "Kenya" }, { "KI", "Kiribati" },
			{ "KP", "Korea, Democratic People's Republic Of" },
			{ "KR", "Korea, Republic Of" }, { "KV", "Kosovo" },
			{ "KW", "Kuwait" }, { "KG", "Kyrgyzstan" },
			{ "LA", "Lao People's Democratic Republic" }, { "LV", "Latvia" },
			{ "LB", "Lebanon" }, { "LS", "Lesotho" }, { "LR", "Liberia" },
			{ "LY", "Libyan Arab Jamahiriya" }, { "LI", "Liechtenstein" },
			{ "LT", "Lithuania" }, { "LU", "Luxembourg" }, { "MO", "Macau" },
			{ "MK", "Macedonia, The Former Yugoslav Republic Of" },
			{ "MG", "Madagascar" }, { "MW", "Malawi" }, { "MY", "Malaysia" },
			{ "MV", "Maldives" }, { "ML", "Mali" }, { "MT", "Malta" },
			{ "MH", "Marshall Islands" }, { "MQ", "Martinique" },
			{ "MR", "Mauritania" }, { "MU", "Mauritius" }, { "YT", "Mayotte" },
			{ "MX", "Mexico" }, { "FM", "Micronesia, Federated States Of" },
			{ "MD", "Moldova, Republic Of" }, { "MC", "Monaco" },
			{ "MN", "Mongolia" }, { "MS", "Montserrat" },
			{ "ME", "Montenegro" }, { "MA", "Morocco" },
			{ "MZ", "Mozambique" }, { "MM", "Myanmar" }, { "NA", "Namibia" },
			{ "NR", "Nauru" }, { "NP", "Nepal" }, { "NL", "Netherlands" },
			{ "AN", "Netherlands Antilles" }, { "NC", "New Caledonia" },
			{ "NZ", "New Zealand" }, { "NI", "Nicaragua" }, { "NE", "Niger" },
			{ "NG", "Nigeria" }, { "NU", "Niue" }, { "NF", "Norfolk Island" },
			{ "MP", "Northern Mariana Islands" }, { "NO", "Norway" },
			{ "OM", "Oman" }, { "PK", "Pakistan" }, { "PW", "Palau" },
			{ "PS", "Palestinian Territory, Occupied" }, { "PA", "Panama" },
			{ "PG", "Papua New Guinea" }, { "PY", "Paraguay" },
			{ "PE", "Peru" }, { "PH", "Philippines" }, { "PN", "Pitcairn" },
			{ "PL", "Poland" }, { "PT", "Portugal" }, { "PR", "Puerto Rico" },
			{ "QA", "Qatar" }, { "RE", "Reunion" }, { "RO", "Romania" },
			{ "RU", "Russian Federation" }, { "RW", "Rwanda" },
			{ "SH", "Saint Helena" }, { "KN", "Saint Kitts And Nevis" },
			{ "LC", "Saint Lucia" }, { "PM", "Saint Pierre And Miquelon" },
			{ "VC", "Saint Vincent And The Grenadines" }, { "WS", "Samoa" },
			{ "SM", "San Marino" }, { "ST", "Sao Tome And Principe" },
			{ "SA", "Saudi Arabia" }, { "SN", "Senegal" }, { "RS", "Serbia" },
			{ "SC", "Seychelles" }, { "SL", "Sierra Leone" },
			{ "SG", "Singapore" }, { "SK", "Slovakia" }, { "SI", "Slovenia" },
			{ "SB", "Solomon Islands" }, { "SO", "Somalia" },
			{ "ZA", "South Africa" },
			{ "GS", "South Georgia And The South Sandwich Islands" },
			{ "ES", "Spain" }, { "LK", "Sri Lanka" }, { "SD", "Sudan" },
			{ "SR", "Suriname" }, { "SJ", "Svalbard And Jan Mayen" },
			{ "SZ", "Swaziland" }, { "SE", "Sweden" }, { "CH", "Switzerland" },
			{ "SY", "Syrian Arab Republic" },
			{ "TW", "Taiwan, Province Of China" }, { "TJ", "Tajikistan" },
			{ "TZ", "Tanzania, United Republic Of" }, { "TH", "Thailand" },
			{ "TG", "Togo" }, { "TK", "Tokelau" }, { "TO", "Tonga" },
			{ "TT", "Trinidad And Tobago" }, { "TN", "Tunisia" },
			{ "TR", "Turkey" }, { "TM", "Turkmenistan" },
			{ "TC", "Turks And Caicos Islands" }, { "TV", "Tuvalu" },
			{ "UG", "Uganda" }, { "UA", "Ukraine" },
			{ "AE", "United Arab Emirates" }, { "GB", "United Kingdom" },
			{ "US", "United States" },
			{ "UM", "United States Minor Outlying Islands" },
			{ "UY", "Uruguay" }, { "UZ", "Uzbekistan" }, { "VU", "Vanuatu" },
			{ "VE", "Venezuela" }, { "VN", "Vi\u1EC7t Nam" },
			{ "VG", "Virgin Islands, British" },
			{ "VI", "Virgin Islands, U.s." }, { "WF", "Wallis And Futuna" },
			{ "EH", "Western Sahara" }, { "YE", "Yemen" }, { "ZM", "Zambia" },
			{ "ZW", "Zimbabwe" } };

	public static final String[][] TIME_ZONES = new String[][] {
			{ "(GMT-11 01:00)Apia, Pago Pago", "-11" },
			{ "(GMT-10 02:00)Honolulu, Papeete", "-10" },
			{ "(GMT-9 03:00)Anchorage, Juneau", "-9" },
			{ "(GMT-8 04:00)Los Angeles, San Francisco, Las Vegas, Vancouver",
					"-8" },
			{ "(GMT-7 05:00)Calgary, Denver", "-7" },
			{ "(GMT-6 06:00)Chicago, Mexico City", "-6" },
			{
					"(GMT-5 07:00)Toronto, New York City, Havana, Bogot\u0102\u0192\u00C2\u00A1, Lima",
					"-5" },
			{
					"(GMT-4 08:00)Asunci\u0102\u0192\u00C2\u00B3n, Halifax, Santiago",
					"-4" },
			{
					"(GMT-3 09:00)Buenos Aires, Montevideo, Rio de Janeiro, S\u0102\u0192\u00C2\u00A3o Paulo",
					"-3" },
			{
					"(GMT-2 10:00)Fernando de Noronha, South Georgia and the South Sandwich Islands",
					"-2" },
			{ "(GMT-1 11:00)Azores, Cape Verde", "-1" },
			{
					"(GMT+0 12:00)Dakar, Casablanca, London, Lisbon, Reykjav\u0102\u0192\u00C2\u00ADk, Tenerife",
					"0" },
			{
					"(GMT+1 13:00)Algiers, Berlin, Kinshasa, Lagos, Paris, Rome, Tunis",
					"1" },
			{
					"(GMT+2 14:00)Istanbul,Athens ,Cairo, Cape Town, Helsinki, Jerusalem",
					"2" },
			{
					"(GMT+3 15:00)Addis Ababa, Baghdad, Moscow, Nairobi, Saint Petersburg",
					"3" },
			{ "(GMT+4 16:00)Baku, Dubai, Mauritius, Samara, Tbilisi ", "4" },
			{ "(GMT+5 17:00)Karachi, Maldives, Tashkent, Yekaterinburg", "5" },
			{ "(GMT+6 18:00)Almaty, Dhaka, Omsk 	", "6" },
			{ "(GMT+7 19:00)Bangkok, Jakarta, Hanoi, Krasnoyarsk", "7" },
			{
					"(GMT+8 20:00)Beijing, Hong Kong, Irkutsk, Kuala Lumpur, Manila, Perth",
					"8" },
			{ "(GMT+9 21:00)Pyongyang, Seoul, Tokyo, Yakutsk", "9" },
			{ "(GMT+10 22:00)Melbourne, Sydney, Vladivostok", "10" },
			{ "(GMT+11 23:00)Magadan, Noum\u0102\u0192\u00C2\u00A9a", "11" },
			{
					"(GMT+12 00:00 (the following day))Auckland, Petropavlovsk-Kamchatsky, Suva",
					"12" },
			{ "(GMT+13 01:00 (the following day))Nuku\u0102\u00C2\u00BBalofa",
					"13" } };
}
